-- Phase 8: RLS policies for advisor role access
-- Advisors must be able to INSERT vehicles and sales.
-- All writes by non-admin roles are restricted to their own records.

-- ── 1. Update helper functions ────────────────────────────────────────────────

-- Include gerente and accounting in admin write access
CREATE OR REPLACE FUNCTION can_write_admin_data()
RETURNS boolean AS $$
  SELECT current_profile_role() IN ('owner', 'partner', 'admin', 'gerente', 'accounting');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- New helper: any active internal user (including advisor)
CREATE OR REPLACE FUNCTION is_internal_user()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND active = true
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- ── 2. VEHICLES ───────────────────────────────────────────────────────────────

-- Allow any internal user to register a vehicle
CREATE POLICY "advisor insert vehicles" ON vehicles
  FOR INSERT
  WITH CHECK (is_internal_user());

-- Allow advisors to update vehicles they created; admins can update all
CREATE POLICY "advisor update own vehicles" ON vehicles
  FOR UPDATE
  USING (
    is_internal_user() AND (
      can_write_admin_data()
      OR created_by = auth.uid()
      OR created_by_user_id = auth.uid()
    )
  );

-- ── 3. VEHICLE MOVEMENTS ──────────────────────────────────────────────────────
-- Required when createVehicle() logs the entry movement

CREATE POLICY "internal insert vehicle movements" ON vehicle_movements
  FOR INSERT
  WITH CHECK (is_internal_user());

-- ── 4. CUSTOMERS ──────────────────────────────────────────────────────────────
-- Required when registering a sale with a new or existing customer

CREATE POLICY "internal insert customers" ON customers
  FOR INSERT
  WITH CHECK (is_internal_user());

CREATE POLICY "internal update customers" ON customers
  FOR UPDATE
  USING (is_internal_user());

-- ── 5. SALES ─────────────────────────────────────────────────────────────────

-- Allow any internal user to register a sale
CREATE POLICY "advisor insert sales" ON sales
  FOR INSERT
  WITH CHECK (is_internal_user());

-- Advisors can update their own sales; admins can update all
CREATE POLICY "advisor update own sales" ON sales
  FOR UPDATE
  USING (
    is_internal_user() AND (
      can_write_admin_data()
      OR created_by_user_id = auth.uid()
    )
  );

-- ── 6. COMMISSIONS ────────────────────────────────────────────────────────────
-- Advisors may need to read commissions linked to their sales

-- (commissions SELECT is already allowed by is_internal_user in rls_policies.sql)
-- INSERT for commissions is admin-only (commissions are generated by admins)

-- ── 7. VEHICLE COSTS ──────────────────────────────────────────────────────────
-- (Already handled in phase2 if applied; advisors don't need to write costs)

-- ── NOTES ─────────────────────────────────────────────────────────────────────
-- Supabase RLS uses OR logic for permissive policies.
-- The existing "write vehicles FOR ALL" policy (admin only) still blocks
-- UPDATE/DELETE for advisors unless the new "advisor update own vehicles" policy
-- also passes. INSERT is now open to all internal users via the new policy.
--
-- IMPORTANT: If SUPABASE_SERVICE_ROLE_KEY is set on Railway, server actions
-- use the admin client and bypass RLS entirely. These policies only matter
-- when falling back to the regular authenticated client.
